import Footer from '@/components/ui/Footer/Footer'
import { Inter } from 'next/font/google'
import './globals.css'
import NextSessionProvider from '../components/Provider/NextSessionProvider'
import QueryProvider from '@/components/Provider/QueryProvider'
import ReduxProvider from '@/components/Provider/ReduxProvider'
import Header from '@/components/ui/Navbar/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'All Tours',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextSessionProvider>
            <QueryProvider>
              <Header />
              {children}
              <Footer />
            </QueryProvider>
          </NextSessionProvider>
        </body>
      </html>
    </ReduxProvider>
  )
}
